### ISSUE TITLE
这个项目是做什么用的？

### ISSUE THREAD

**Issue by rysonliu** [wangle201210/LaravelWorkflowDatabase#1]
请问，这个项目是做什么用的？工作流吗？怎么使用？谢谢。

**Comment by wangle201210** [comment]
是用作工作流
工作流本身是用config文件控制的
但是为了方便管理员（或者是客户）使用，就把配置项放放到数据库
简单来讲就是方便用户修改

**Comment by wangle201210** [comment]
还有一点就是为了方便绑定角色和操作
即哪个角色可以执行哪步操作

**Comment by rysonliu** [comment]
这里的工作流就是手动定义的状态机是吗？不是那种可以图形化自由设计流程和审批人的工作流。

**Comment by wangle201210** [comment]
界面是前端的事情了~
